# Joseph Bradford
# CS3580 Data Science Algorithms
# Assignment 1 : Introduction to Python

# First Specification - Print Name
print("Joseph Bradford")

# Second Specification - Calculate Sum of Digits of 100 factorial

factorial = 1
sumOfDigits = 0

# calculate 100!
for x in range(1, 101):
    factorial = x * factorial

# Iterate through digits and calculate sum
for character in str(factorial):
    sumOfDigits += int(character)

print('Sum of digits in 100!: ' + str(sumOfDigits))

# Third specification - Calculate index of first 1000 digit fibonacci number

# First two fibonacci numbers
one = 1
two = 1
# starting index is 2
index = 2

# Iteratively count fibonacci numbers until a 1000 digit number is reached
while len(str(two)) < 1000:
    fibonacci = one + two
    index += 1
    one = two
    two = fibonacci

print('Index of first 1000 digit Fibonacci number: ' + str(index))

# Fourth Specification - largest palindrome generated by multiplying 3 digit numbers

maxPalindrome = 0

# Brute force multiply all combinations of 3 digit numbers
for x in range(100, 1000):
    for y in range(100, 1000):
        temp = x * y
        # Is it a palindrome?
        if str(temp) == str(temp)[::-1]:
            # Is it the largest palindrome we have seen so far?
            if temp > maxPalindrome:
                maxPalindrome = temp

print('Largest palindrome multiple of 3 digit numbers: ' + str(maxPalindrome))






